// World Clock 2.0.0 — native C++ / Win32 / Direct2D / Windows Acrylic.
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <commdlg.h>
#include <shellapi.h>
#include <shlobj.h>
#include <dwmapi.h>
#include <d2d1_1.h>
#include <wincodec.h>
#include <dwrite.h>
#include <winhttp.h>
#include <wrl/client.h>
#include <algorithm>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <thread>
#include <vector>
#include "json.hpp"
#include "resource.h"
using json = nlohmann::json;
using Microsoft::WRL::ComPtr;
namespace fs = std::filesystem;
#include "zones.h"
constexpr UINT WM_NET=WM_APP+1, WM_TRAY=WM_APP+2;
constexpr int CMD_ADD=200,CMD_SAVE=201,CMD_EXPORT=202,CMD_STARTUP=203,CMD_EXIT=204,CMD_SHOW=205,CMD_HORIZONTAL=206,CMD_VERTICAL=207,CMD_SETTINGS=208,CMD_REMOVE=209,CMD_WEATHER=210,CMD_ABOUT=211,CMD_CHANGE=212,CMD_ALIGN_BASE=4000;
HICON g_iconSmall=nullptr,g_iconLarge=nullptr;
HINSTANCE g_instance; HWND g_main=nullptr; UINT g_taskbarCreated=0;
ComPtr<ID2D1Factory> g_d2d; ComPtr<IDWriteFactory> g_write;
std::map<std::wstring,DYNAMIC_TIME_ZONE_INFORMATION> g_windowsZones;
fs::path g_config; bool g_testing=false,g_quitting=false; uint64_t g_nextId=1;
std::wstring wide(const std::string& s){if(s.empty())return {};int n=MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),nullptr,0);std::wstring w(n,0);MultiByteToWideChar(CP_UTF8,0,s.data(),(int)s.size(),w.data(),n);return w;}
std::string utf8(const std::wstring& w){if(w.empty())return {};int n=WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),nullptr,0,nullptr,nullptr);std::string s(n,0);WideCharToMultiByte(CP_UTF8,0,w.data(),(int)w.size(),s.data(),n,nullptr,nullptr);return s;}
std::string str(const json& j,const char* k,const std::string& d=""){auto it=j.find(k);return it!=j.end()&&it->is_string()?it->get<std::string>():d;}
bool flag(const json& j,const char* k,bool d=false){auto it=j.find(k);return it!=j.end()&&it->is_boolean()?it->get<bool>():d;}
double number(const json& j,const char* k,double d=0){auto it=j.find(k);return it!=j.end()&&it->is_number()?it->get<double>():d;}
double nowSeconds(){return std::chrono::duration<double>(std::chrono::system_clock::now().time_since_epoch()).count();}
SYSTEMTIME systemAt(double s){ULARGE_INTEGER x;x.QuadPart=(ULONGLONG)((s+11644473600.0)*10000000.0);FILETIME ft={x.LowPart,x.HighPart};SYSTEMTIME st{};FileTimeToSystemTime(&ft,&st);return st;}
long long ticksOf(const SYSTEMTIME& st){FILETIME ft{};SystemTimeToFileTime(&st,&ft);ULARGE_INTEGER x;x.LowPart=ft.dwLowDateTime;x.HighPart=ft.dwHighDateTime;return (long long)x.QuadPart;}
std::string dateOf(const SYSTEMTIME& st){char b[32];sprintf_s(b,"%04u-%02u-%02u",st.wYear,st.wMonth,st.wDay);return b;}
void initZones(){for(DWORD i=0;;++i){DYNAMIC_TIME_ZONE_INFORMATION z{};if(EnumDynamicTimeZoneInformation(i,&z)!=ERROR_SUCCESS)break;g_windowsZones[z.TimeZoneKeyName]=z;}}
std::wstring windowsZone(std::string zone){static const std::map<std::string,std::string> aliases={{"Europe/Kyiv","Europe/Kiev"},{"Asia/Kolkata","Asia/Calcutta"},{"Asia/Kathmandu","Asia/Katmandu"},{"Asia/Yangon","Asia/Rangoon"},{"America/Nuuk","America/Godthab"}};auto a=aliases.find(zone);if(a!=aliases.end())zone=a->second;if(zone=="UTC"||zone=="Etc/UTC"||zone=="Etc/GMT")return L"UTC";auto it=ZONE_MAP.find(zone);return it==ZONE_MAP.end()?L"":it->second;}
bool zoneSupported(const std::string& zone){return g_windowsZones.count(windowsZone(zone))!=0;}
SYSTEMTIME localAt(const std::string& zone,double seconds){SYSTEMTIME utc=systemAt(seconds),local{};auto it=g_windowsZones.find(windowsZone(zone));if(it==g_windowsZones.end()||!SystemTimeToTzSpecificLocalTimeEx(&it->second,&utc,&local))return utc;return local;}
std::wstring deltaAt(const std::string& zone,double seconds){auto target=localAt(zone,seconds);SYSTEMTIME utc=systemAt(seconds),local{};SystemTimeToTzSpecificLocalTimeEx(nullptr,&utc,&local);long m=(long)((ticksOf(target)-ticksOf(local))/600000000LL);if(m==0)return L"本地同时间";long n=std::abs(m);std::wstring s=(m>0?L"+":L"−")+std::to_wstring(n/60)+L"h";if(n%60)s+=std::to_wstring(n%60)+L"m";return s;}
const char* SHOW_KEYS[]={"city","region","date","weekday","offset","weather","seconds","sun","sun_times"};
json defaultShow(){return {{"city",true},{"region",false},{"date",true},{"weekday",true},{"offset",true},{"weather",true},{"seconds",true},{"sun",true},{"sun_times",false}};}
std::vector<json> presets(){return {
{{"name","北京"},{"region","中国"},{"zone","Asia/Shanghai"},{"lat",39.9042},{"lon",116.4074}},
{{"name","迪拜"},{"region","阿联酋"},{"zone","Asia/Dubai"},{"lat",25.2048},{"lon",55.2708}},
{{"name","卢萨卡"},{"region","赞比亚"},{"zone","Africa/Lusaka"},{"lat",-15.3875},{"lon",28.3228}},
{{"name","科伦坡"},{"region","斯里兰卡"},{"zone","Asia/Colombo"},{"lat",6.9271},{"lon",79.8612}},
{{"name","伦敦"},{"region","英国"},{"zone","Europe/London"},{"lat",51.5085},{"lon",-0.1257}},
{{"name","纽约"},{"region","美国"},{"zone","America/New_York"},{"lat",40.7143},{"lon",-74.006}},
{{"name","东京"},{"region","日本"},{"zone","Asia/Tokyo"},{"lat",35.6895},{"lon",139.6917}},
{{"name","新加坡"},{"region","新加坡"},{"zone","Asia/Singapore"},{"lat",1.2897},{"lon",103.8501}}};}
json normalized(json s){
if(!s.is_object()||!zoneSupported(str(s,"zone")))throw std::runtime_error("Unsupported time zone");
auto show=defaultShow();if(s.contains("show")&&s["show"].is_object())for(auto k:SHOW_KEYS)show[k]=flag(s["show"],k,show[k].get<bool>());s["show"]=show;
s["name"]=str(s,"name",str(s,"zone"));s["region"]=str(s,"region");s["x"]=(int)number(s,"x",80);s["y"]=(int)number(s,"y",50);s["top"]=flag(s,"top",true);s["glass"]=flag(s,"glass",true);s["theme"]=str(s,"theme",flag(s,"dark")?"dark":"system");s["color_mode"]=str(s,"color_mode","system");s["color"]=str(s,"color","#d7d8d8");if(!flag(s,"opacity_direction")){s["transparency"]=100-number(s,"transparency",std::round((255-number(s,"alpha",210))*100/255));s["opacity_direction"]=true;}s["transparency"]=std::clamp((int)number(s,"transparency",std::round((255-number(s,"alpha",210))*100/255)),0,100);
for(auto p:presets())if(str(p,"zone")==str(s,"zone")&&!s.contains("lat")){s["lat"]=p["lat"];s["lon"]=p["lon"];if(str(s,"region").empty())s["region"]=p["region"];}
if(s.contains("lat")&&(!s["lat"].is_number()||!s.contains("lon")||!s["lon"].is_number()||std::abs(number(s,"lat"))>90||std::abs(number(s,"lon"))>180)){s.erase("lat");s.erase("lon");}return s;}
bool systemDark(){DWORD v=1,n=sizeof(v);RegGetValueW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize",L"AppsUseLightTheme",RRF_RT_REG_DWORD,nullptr,&v,&n);return v==0;}
struct Sun{int day=-1;double rise=0,set=0;};
Sun sunFor(const json& w,const std::string& zone,double now){Sun s;auto today=dateOf(localAt(zone,now));if(w.contains("days")&&w["days"].is_array())for(const auto& row:w["days"]){if(str(row,"date")==today){s.rise=number(row,"rise");s.set=number(row,"set");if(s.rise>0&&s.set>s.rise){s.day=now>=s.rise&&now<s.set?1:0;return s;}}}if(std::abs(now-number(w,"current_time"))<=1800&&w.contains("is_day")&&w["is_day"].is_number())s.day=(int)number(w,"is_day",-1);return s;}
std::wstring weatherName(int c){if(c==0)return L"晴";if(c==1||c==2)return L"多云";if(c==3)return L"阴";if(c==45||c==48)return L"雾";if(c>=51&&c<=57)return L"毛毛雨";if((c>=61&&c<=67)||(c>=80&&c<=82))return L"雨";if((c>=71&&c<=77)||c==85||c==86)return L"雪";if(c>=95)return L"雷雨";return L"天气未知";}
struct Card{uint64_t id=g_nextId++;HWND hwnd=nullptr;json state;float dpi=96;bool pending=false;double retryAt=0;std::wstring error;ComPtr<ID2D1RenderTarget> target;ComPtr<IWICBitmap> bitmap;ComPtr<ID2D1Bitmap> blur;
HRESULT renderResult=S_OK;double captureAt=0;RECT capturedRect{};bool captureOK=false;DWORD captureError=0;bool testBlurFixture=false;
int testCornerAlpha=-1,testBackgroundAlpha=-1,testMaxAlpha=-1,testSoftEdges=0;
ComPtr<ID2D1SolidColorBrush> brush;
int height()const{const auto& s=state["show"];return 68+22*((flag(s,"city")||flag(s,"region")||flag(s,"sun"))+(flag(s,"date")||flag(s,"weekday")||flag(s,"offset"))+flag(s,"weather")+flag(s,"sun_times"));}
int px(int v)const{return MulDiv(v,(int)dpi,96);}};
std::vector<std::unique_ptr<Card>> g_cards;
Card* findCard(uint64_t id){for(auto& c:g_cards)if(c->id==id)return c.get();return nullptr;}
LRESULT CALLBACK CardProc(HWND,UINT,WPARAM,LPARAM);LRESULT CALLBACK MainProc(HWND,UINT,WPARAM,LPARAM);
void save(bool notify=false);void refresh(bool force=false,Card* only=nullptr);void cardSettings(Card*);void chooseCity(Card* target=nullptr);void updateCard(Card*);void addCard(json);
void notify(const std::wstring& title,const std::wstring& message){if(g_testing)return;NOTIFYICONDATAW n{sizeof(n)};n.hWnd=g_main;n.uID=1;n.uFlags=NIF_INFO;wcsncpy_s(n.szInfoTitle,title.c_str(),_TRUNCATE);wcsncpy_s(n.szInfo,message.c_str(),_TRUNCATE);n.dwInfoFlags=NIIF_INFO;Shell_NotifyIconW(NIM_MODIFY,&n);}
void tray(){if(g_testing)return;NOTIFYICONDATAW n{sizeof(n)};n.hWnd=g_main;n.uID=1;n.uFlags=NIF_ICON|NIF_MESSAGE|NIF_TIP;n.uCallbackMessage=WM_TRAY;n.hIcon=g_iconSmall;wcscpy_s(n.szTip,L"世界时钟 2.0.0 · C++");Shell_NotifyIconW(NIM_ADD,&n);}
std::wstring executable(){std::wstring s(32768,0);DWORD n=GetModuleFileNameW(nullptr,s.data(),(DWORD)s.size());s.resize(n);return s;}
bool autoStart(){DWORD n=0;return RegGetValueW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",L"WorldClockPython",RRF_RT_REG_SZ,nullptr,nullptr,&n)==ERROR_SUCCESS;}
bool setAutoStart(bool on){HKEY key;auto r=RegCreateKeyExW(HKEY_CURRENT_USER,L"Software\\Microsoft\\Windows\\CurrentVersion\\Run",0,nullptr,0,KEY_SET_VALUE,nullptr,&key,nullptr);if(r!=ERROR_SUCCESS)return false;if(on){auto command=L"\""+executable()+L"\" --startup";r=RegSetValueExW(key,L"WorldClockPython",0,REG_SZ,(const BYTE*)command.c_str(),(DWORD)((command.size()+1)*sizeof(wchar_t)));}else{r=RegDeleteValueW(key,L"WorldClockPython");if(r==ERROR_FILE_NOT_FOUND)r=ERROR_SUCCESS;}RegCloseKey(key);return r==ERROR_SUCCESS;}
void writeSettings(const fs::path& file,const json& data){fs::create_directories(file.parent_path());auto temp=file;temp+=L".tmp";{std::ofstream out(temp,std::ios::binary);out<<data.dump(2);out.flush();if(!out)throw std::runtime_error("Cannot write settings");}if(!MoveFileExW(temp.c_str(),file.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw std::runtime_error("Cannot replace settings");}
json settings(){json rows=json::array();for(auto& c:g_cards){RECT r;GetWindowRect(c->hwnd,&r);c->state["x"]=r.left;c->state["y"]=r.top;rows.push_back(c->state);}return {{"version","2.0.0"},{"engine","native-cpp"},{"cards",rows}};}
void save(bool notice){try{writeSettings(g_config,settings());if(notice)notify(L"已保存",L"卡片位置和设置已保存到本地。");}catch(...){notify(L"保存失败",L"请检查设置目录是否可写。");}}
void exportSettings(){wchar_t file[32768]=L"world-clock-settings.json";OPENFILENAMEW o{sizeof(o)};o.hwndOwner=g_main;o.lpstrFilter=L"JSON 文件\0*.json\0\0";o.lpstrFile=file;o.nMaxFile=32768;o.Flags=OFN_OVERWRITEPROMPT|OFN_PATHMUSTEXIST;o.lpstrDefExt=L"json";if(GetSaveFileNameW(&o))try{writeSettings(file,settings());}catch(...){MessageBoxW(g_main,L"导出失败",L"世界时钟",MB_OK|MB_ICONERROR);}}
void load(){try{if(fs::exists(g_config)){std::ifstream in(g_config);auto data=json::parse(in);auto rows=data.is_array()?data:data.value("cards",json::array());if(rows.is_array())for(auto s:rows){if(g_cards.size()>=30)break;try{if(data.is_array())s["top"]=true;addCard(s);}catch(...){}}}}catch(...){std::error_code ec;auto backup=g_config;backup+=L".unreadable-backup";fs::copy_file(g_config,backup,fs::copy_options::overwrite_existing,ec);}if(g_cards.empty()){auto p=presets();for(int i=0;i<3;i++){p[i]["x"]=160+i*280;p[i]["y"]=50;addCard(p[i]);}}}
RECT workArea(HWND h){MONITORINFO info{sizeof(info)};GetMonitorInfoW(MonitorFromWindow(h,MONITOR_DEFAULTTONEAREST),&info);return info.rcWork;}
void clampCard(Card* c){RECT r;GetWindowRect(c->hwnd,&r);RECT a=workArea(c->hwnd);int x=std::clamp((int)r.left,(int)a.left,std::max((int)a.left,(int)(a.right-(r.right-r.left))));int y=std::clamp((int)r.top,(int)a.top,std::max((int)a.top,(int)(a.bottom-(r.bottom-r.top))));SetWindowPos(c->hwnd,nullptr,x,y,0,0,SWP_NOZORDER|SWP_NOSIZE|SWP_NOACTIVATE);}
bool darkCard(Card* c){auto t=str(c->state,"theme");return t=="dark"||(t=="system"&&systemDark());}
D2D1_COLOR_F background(Card* c){DWORD color=darkCard(c)?0x202020:0xfafafa;if(str(c->state,"color_mode")=="custom"){std::string s=str(c->state,"color");if(s.size()==7&&s[0]=='#')try{color=std::stoul(s.substr(1),nullptr,16);}catch(...){}}float alpha=(float)number(c->state,"transparency",82)/100.f;

return D2D1::ColorF(color,alpha);}
// Background shape, opacity and highlight are rendered into a premultiplied bitmap.
void paint(Card* c);
void refreshStyle(Card* c){paint(c);}
void updateCard(Card* c){c->dpi=(float)GetDpiForWindow(c->hwnd);SetWindowPos(c->hwnd,flag(c->state,"top",true)?HWND_TOPMOST:HWND_NOTOPMOST,0,0,c->px(260),c->px(c->height()),SWP_NOMOVE|SWP_NOACTIVATE);refreshStyle(c);InvalidateRect(c->hwnd,nullptr,FALSE);}
void addCard(json state){auto c=std::make_unique<Card>();c->state=normalized(state);auto raw=c.get();HWND h=CreateWindowExW(WS_EX_LAYERED|WS_EX_TOOLWINDOW|(flag(c->state,"top",true)?WS_EX_TOPMOST:0),L"WorldClockCard",wide(str(c->state,"name")).c_str(),WS_POPUP,(int)number(c->state,"x"),(int)number(c->state,"y"),260,c->height(),nullptr,nullptr,g_instance,raw);if(!h)throw std::runtime_error("Window creation failed");raw->hwnd=h;g_cards.push_back(std::move(c));updateCard(raw);clampCard(raw);ShowWindow(h,SW_SHOWNOACTIVATE);paint(raw);}
ComPtr<IWICImagingFactory> g_wic;
void resetGraphics(Card* c){c->brush.Reset();c->blur.Reset();c->bitmap.Reset();c->target.Reset();c->captureAt=0;}
HRESULT initGraphics(Card* c){
    RECT r;GetClientRect(c->hwnd,&r);HRESULT hr=g_wic->CreateBitmap(std::max(1L,r.right),std::max(1L,r.bottom),GUID_WICPixelFormat32bppPBGRA,WICBitmapCacheOnLoad,&c->bitmap);if(FAILED(hr))return hr;
    auto props=D2D1::RenderTargetProperties(D2D1_RENDER_TARGET_TYPE_SOFTWARE,D2D1::PixelFormat(DXGI_FORMAT_B8G8R8A8_UNORM,D2D1_ALPHA_MODE_PREMULTIPLIED),c->dpi,c->dpi);
    hr=g_d2d->CreateWicBitmapRenderTarget(c->bitmap.Get(),props,&c->target);if(FAILED(hr))return hr;
    c->target->SetAntialiasMode(D2D1_ANTIALIAS_MODE_PER_PRIMITIVE);c->target->SetTextAntialiasMode(D2D1_TEXT_ANTIALIAS_MODE_GRAYSCALE);
    return c->target->CreateSolidColorBrush(D2D1::ColorF(0x000000),&c->brush);
}
void captureBackground(Card* c){
    RECT r;GetWindowRect(c->hwnd,&r);if(c->blur&&EqualRect(&r,&c->capturedRect)&&nowSeconds()-c->captureAt<1)return;
    int width=r.right-r.left,height=r.bottom-r.top;if(width<=0||height<=0)return;
    HDC screen=GetDC(nullptr);if(!screen){c->error=L"GetDC: "+std::to_wstring(GetLastError());return;}HDC dc=CreateCompatibleDC(screen);HBITMAP image=CreateCompatibleBitmap(screen,width,height);
    if(!dc||!image){if(image)DeleteObject(image);if(dc)DeleteDC(dc);ReleaseDC(nullptr,screen);return;}
    auto old=SelectObject(dc,image);
    // Deliberately omit CAPTUREBLT: exclude layered clocks, with no hide/move/opacity toggling.
    BOOL ok=BitBlt(dc,0,0,width,height,screen,r.left,r.top,SRCCOPY);c->captureError=ok?0:GetLastError();
    // The isolated test desktop may deny screen reads. Exercise the same blur path
    // with a deterministic fixture, recording separately that live capture was unavailable.
    bool fixture=g_testing&&!ok;
    if(fixture){RECT all{0,0,width,height};FillRect(dc,&all,(HBRUSH)GetStockObject(WHITE_BRUSH));for(int y=0;y<height;y+=16)for(int x=0;x<width;x+=16)if((x/16+y/16)%2){RECT cell{x,y,std::min(x+16,width),std::min(y+16,height)};FillRect(dc,&cell,(HBRUSH)GetStockObject(BLACK_BRUSH));}}

    SelectObject(dc,old);DeleteDC(dc);ReleaseDC(nullptr,screen);
    ComPtr<IWICBitmap> raw;HRESULT hr=(ok||fixture)?g_wic->CreateBitmapFromHBITMAP(image,nullptr,WICBitmapIgnoreAlpha,&raw):E_FAIL;
    DeleteObject(image);ComPtr<IWICBitmapScaler> downsample;ComPtr<ID2D1Bitmap> blurred;
    if(SUCCEEDED(hr))hr=g_wic->CreateBitmapScaler(&downsample);
    if(SUCCEEDED(hr))hr=downsample->Initialize(raw.Get(),std::max(2,width/14),std::max(2,height/14),WICBitmapInterpolationModeFant);
    ComPtr<IWICFormatConverter> converted;
    if(SUCCEEDED(hr))hr=g_wic->CreateFormatConverter(&converted);
    if(SUCCEEDED(hr))hr=converted->Initialize(downsample.Get(),GUID_WICPixelFormat32bppPBGRA,WICBitmapDitherTypeNone,nullptr,0,WICBitmapPaletteTypeCustom);
    if(SUCCEEDED(hr))hr=c->target->CreateBitmapFromWicBitmap(converted.Get(),nullptr,&blurred);
    if(SUCCEEDED(hr)){c->blur=blurred;c->capturedRect=r;c->captureAt=nowSeconds();c->captureOK=ok!=FALSE;c->testBlurFixture=fixture;}
}
HRESULT presentLayered(Card* c){
    UINT w,h;c->bitmap->GetSize(&w,&h);std::vector<BYTE> bytes((size_t)w*h*4);HRESULT hr=c->bitmap->CopyPixels(nullptr,w*4,(UINT)bytes.size(),bytes.data());if(FAILED(hr))return hr;
    if(g_testing){c->testCornerAlpha=bytes[3];c->testBackgroundAlpha=bytes[((h-5)*w+w/2)*4+3];c->testMaxAlpha=0;c->testSoftEdges=0;
        for(UINT y=0;y<h;y++)for(UINT x=0;x<w;x++){int alpha=bytes[(y*w+x)*4+3];c->testMaxAlpha=std::max(c->testMaxAlpha,alpha);if(x<12&&y<12&&alpha>0&&alpha<255)c->testSoftEdges++;}}
    BITMAPINFO info{};info.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);info.bmiHeader.biWidth=w;info.bmiHeader.biHeight=-(LONG)h;info.bmiHeader.biPlanes=1;info.bmiHeader.biBitCount=32;info.bmiHeader.biCompression=BI_RGB;
    HDC dc=CreateCompatibleDC(nullptr);void* pixels=nullptr;HBITMAP dib=CreateDIBSection(dc,&info,DIB_RGB_COLORS,&pixels,nullptr,0);
    if(!dc||!dib){if(dib)DeleteObject(dib);if(dc)DeleteDC(dc);return E_FAIL;}memcpy(pixels,bytes.data(),bytes.size());
    auto old=SelectObject(dc,dib);RECT r;GetWindowRect(c->hwnd,&r);POINT destination{r.left,r.top},source{};SIZE size{(LONG)w,(LONG)h};BLENDFUNCTION blend{AC_SRC_OVER,0,255,AC_SRC_ALPHA};
    BOOL ok=UpdateLayeredWindow(c->hwnd,nullptr,&destination,&size,dc,&source,0,&blend,ULW_ALPHA);
    SelectObject(dc,old);DeleteObject(dib);DeleteDC(dc);return ok?S_OK:E_FAIL;
}
void drawBackdrop(Card* c){
    auto rt=c->target.Get();auto bg=background(c);if(bg.a<=0)return;
    ComPtr<ID2D1RoundedRectangleGeometry> shape;g_d2d->CreateRoundedRectangleGeometry(D2D1::RoundedRect(D2D1::RectF(0,0,260,(float)c->height()),14,14),&shape);
    ComPtr<ID2D1Layer> layer;rt->CreateLayer(nullptr,&layer);
    // One layer opacity multiplies blur, tint, highlight and edge coverage together.
    rt->PushLayer(D2D1::LayerParameters(D2D1::InfiniteRect(),shape.Get(),D2D1_ANTIALIAS_MODE_PER_PRIMITIVE,D2D1::IdentityMatrix(),bg.a),layer.Get());
    c->brush->SetColor(D2D1::ColorF(bg.r,bg.g,bg.b,1));rt->FillRectangle(D2D1::RectF(0,0,260,(float)c->height()),c->brush.Get());
    if(flag(c->state,"glass",true)&&c->blur){rt->DrawBitmap(c->blur.Get(),D2D1::RectF(0,0,260,(float)c->height()),1,D2D1_BITMAP_INTERPOLATION_MODE_LINEAR);c->brush->SetColor(D2D1::ColorF(bg.r,bg.g,bg.b,.40f));rt->FillRectangle(D2D1::RectF(0,0,260,(float)c->height()),c->brush.Get());}
    D2D1_GRADIENT_STOP stops[]={{0,D2D1::ColorF(0xffffff,.20f)},{.5f,D2D1::ColorF(0xffffff,.03f)},{1,D2D1::ColorF(0xffffff,0)}};
    ComPtr<ID2D1GradientStopCollection> collection;ComPtr<ID2D1LinearGradientBrush> shine;
    if(SUCCEEDED(rt->CreateGradientStopCollection(stops,3,&collection))&&SUCCEEDED(rt->CreateLinearGradientBrush(D2D1::LinearGradientBrushProperties(D2D1::Point2F(0,0),D2D1::Point2F(0,(float)c->height())),collection.Get(),&shine)))rt->FillRectangle(D2D1::RectF(0,0,260,(float)c->height()),shine.Get());
    rt->PopLayer();
}
void paint(Card* c){PAINTSTRUCT ps;BeginPaint(c->hwnd,&ps);
if(!c->target){resetGraphics(c);c->renderResult=initGraphics(c);if(FAILED(c->renderResult)){resetGraphics(c);EndPaint(c->hwnd,&ps);return;}}
if(c->target&&c->brush){if(flag(c->state,"glass",true)&&number(c->state,"transparency")>0)captureBackground(c);auto rt=c->target.Get();rt->BeginDraw();rt->Clear(D2D1::ColorF(0x000000,0.f));drawBackdrop(c);
auto bg=background(c);bool dark=str(c->state,"color_mode")=="custom"?(bg.r*.2126+bg.g*.7152+bg.b*.0722)<.45:darkCard(c);c->brush->SetColor(D2D1::ColorF(dark?0xf4f6fa:0x202833));
auto text=[&](std::wstring s,float y,float size,float h,bool bold=false,float right=250.f){ComPtr<IDWriteTextFormat> format;if(SUCCEEDED(g_write->CreateTextFormat(size>=30?L"Segoe UI":L"Microsoft YaHei UI",nullptr,bold?DWRITE_FONT_WEIGHT_SEMI_BOLD:DWRITE_FONT_WEIGHT_NORMAL,DWRITE_FONT_STYLE_NORMAL,DWRITE_FONT_STRETCH_NORMAL,size,L"zh-CN",&format))){format->SetTextAlignment(DWRITE_TEXT_ALIGNMENT_CENTER);format->SetParagraphAlignment(DWRITE_PARAGRAPH_ALIGNMENT_CENTER);format->SetWordWrapping(DWRITE_WORD_WRAPPING_NO_WRAP);rt->DrawText(s.c_str(),(UINT32)s.size(),format.Get(),D2D1::RectF(10,y,right,y+h),c->brush.Get(),D2D1_DRAW_TEXT_OPTIONS_CLIP);}};
auto& s=c->state["show"];double now=nowSeconds();auto zone=str(c->state,"zone");auto st=localAt(zone,now);json w=c->state.value("weather",json::object());auto sun=sunFor(w,zone,now);float y=10;
if(flag(s,"city")||flag(s,"region")||flag(s,"sun")){std::wstring header=flag(s,"city")?wide(str(c->state,"name")):L"";if(flag(s,"region"))header+=L" "+wide(str(c->state,"region"));text(header,y,13,22,true,flag(s,"sun")?226.f:250.f);if(flag(s,"sun")){float x=240,cy=y+11;if(sun.day==1){rt->FillEllipse(D2D1::Ellipse(D2D1::Point2F(x,cy),3.5,3.5),c->brush.Get());for(int i=0;i<8;i++){float a=i*3.14159265f/4;rt->DrawLine(D2D1::Point2F(x+5*cosf(a),cy+5*sinf(a)),D2D1::Point2F(x+8*cosf(a),cy+8*sinf(a)),c->brush.Get(),1);}}else if(sun.day==0){ComPtr<ID2D1PathGeometry> path;ComPtr<ID2D1GeometrySink> sink;ComPtr<ID2D1Factory> renderFactory;c->target->GetFactory(&renderFactory);renderFactory->CreatePathGeometry(&path);path->Open(&sink);sink->BeginFigure(D2D1::Point2F(x+3,cy-7),D2D1_FIGURE_BEGIN_FILLED);sink->AddBezier(D2D1::BezierSegment(D2D1::Point2F(x-10,cy-8),D2D1::Point2F(x-10,cy+9),D2D1::Point2F(x+5,cy+6)));sink->AddBezier(D2D1::BezierSegment(D2D1::Point2F(x-3,cy+5),D2D1::Point2F(x-5,cy-2),D2D1::Point2F(x+3,cy-7)));sink->EndFigure(D2D1_FIGURE_END_CLOSED);sink->Close();rt->FillGeometry(path.Get(),c->brush.Get());}else rt->DrawEllipse(D2D1::Ellipse(D2D1::Point2F(x,cy),5,5),c->brush.Get());}y+=22;}
wchar_t b[64];if(flag(s,"seconds"))swprintf_s(b,L"%02u:%02u:%02u",st.wHour,st.wMinute,st.wSecond);else swprintf_s(b,L"%02u:%02u",st.wHour,st.wMinute);text(b,y,36,48,true);y+=48;
if(flag(s,"date")||flag(s,"weekday")||flag(s,"offset")){std::wstring footer;if(flag(s,"date"))footer=wide(dateOf(st));const wchar_t* weekdays[]={L"周日",L"周一",L"周二",L"周三",L"周四",L"周五",L"周六"};if(flag(s,"weekday"))footer+=L"  "+std::wstring(weekdays[st.wDayOfWeek]);if(flag(s,"offset"))footer+=L"  "+deltaAt(zone,now);text(footer,y,11,22);y+=22;}
if(flag(s,"weather")){std::wstring label;if(w.contains("temp")&&w["temp"].is_number()){swprintf_s(b,L"%.1f°C  ",number(w,"temp"));label=b;label+=weatherName((int)number(w,"code",-1));if(!c->error.empty()||now-number(w,"fetched")>3600)label+=L" · 缓存";}else label=c->pending?L"正在获取天气…":L"天气暂不可用";text(label,y,12,22);y+=22;}
if(flag(s,"sun_times")){std::wstring label=L"日出 / 日落 暂不可用";if(sun.rise&&sun.set){auto a=localAt(zone,sun.rise),z=localAt(zone,sun.set);swprintf_s(b,L"日出 %02u:%02u   日落 %02u:%02u",a.wHour,a.wMinute,z.wHour,z.wMinute);label=b;}text(label,y,11,22);}
c->renderResult=rt->EndDraw();if(SUCCEEDED(c->renderResult))c->renderResult=presentLayered(c);if(FAILED(c->renderResult))resetGraphics(c);}EndPaint(c->hwnd,&ps);}
std::wstring escaped(const std::string& s){std::string o;const char* h="0123456789ABCDEF";for(unsigned char c:s){if((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='-'||c=='_'||c=='.'||c=='~')o+=(char)c;else{o+='%';o+=h[c>>4];o+=h[c&15];}}return wide(o);}
struct Internet{HINTERNET h;Internet(HINTERNET value):h(value){if(!h)throw std::runtime_error("Network handle failed");}~Internet(){WinHttpCloseHandle(h);}operator HINTERNET()const{return h;}};
json https(const wchar_t* host,const std::wstring& path){Internet session(WinHttpOpen(L"WorldClock/2.0.0",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0));WinHttpSetTimeouts(session,10000,10000,15000,15000);Internet connection(WinHttpConnect(session,host,INTERNET_DEFAULT_HTTPS_PORT,0));Internet request(WinHttpOpenRequest(connection,L"GET",path.c_str(),nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,WINHTTP_FLAG_SECURE));if(!WinHttpSendRequest(request,WINHTTP_NO_ADDITIONAL_HEADERS,0,WINHTTP_NO_REQUEST_DATA,0,0,0)||!WinHttpReceiveResponse(request,nullptr))throw std::runtime_error("HTTPS request failed: " + std::to_string(GetLastError()));DWORD code=0,size=sizeof(code);WinHttpQueryHeaders(request,WINHTTP_QUERY_STATUS_CODE|WINHTTP_QUERY_FLAG_NUMBER,nullptr,&code,&size,nullptr);if(code!=200)throw std::runtime_error("HTTP status "+std::to_string(code));std::string body;char b[8192];DWORD got;while(true){if(!WinHttpReadData(request,b,sizeof(b),&got))throw std::runtime_error("Network read failed");if(!got)break;body.append(b,got);if(body.size()>4*1024*1024)throw std::runtime_error("Response too large");}return json::parse(body);}
json weatherRequest(const json& state){auto zone=str(state,"zone");auto path=L"/v1/forecast?latitude="+std::to_wstring(number(state,"lat"))+L"&longitude="+std::to_wstring(number(state,"lon"))+L"&current=temperature_2m,weather_code,is_day&daily=sunrise,sunset&forecast_days=3&timeformat=unixtime&timezone="+escaped(zone);auto data=https(L"api.open-meteo.com",path);auto current=data.at("current");json days=json::array();auto daily=data.at("daily");for(size_t i=0;i<daily.at("sunrise").size();i++){if(!daily["sunrise"][i].is_number()||!daily["sunset"][i].is_number())continue;double rise=daily["sunrise"][i].get<double>(),set=daily["sunset"][i].get<double>();days.push_back({{"date",dateOf(localAt(zone,rise))},{"rise",rise},{"set",set}});}return {{"temp",current.at("temperature_2m")},{"code",current.at("weather_code")},{"is_day",current.at("is_day")},{"current_time",current.at("time")},{"fetched",nowSeconds()},{"days",days}};}
struct NetResult{bool search=false;uint64_t id=0;unsigned generation=0;std::string identity;json data;std::wstring error;};
std::string identity(const json& s){return str(s,"zone")+":"+std::to_string(number(s,"lat"))+":"+std::to_string(number(s,"lon"));}
void refresh(bool force,Card* only){if(g_testing)return;for(auto& ptr:g_cards){Card* c=ptr.get();if(only&&c!=only)continue;auto& s=c->state["show"];if(c->pending||!c->state.contains("lat")||(!flag(s,"weather")&&!flag(s,"sun")&&!flag(s,"sun_times")))continue;double now=nowSeconds();if(!force&&(now<c->retryAt||now-number(c->state.value("weather",json::object()),"fetched")<900))continue;c->pending=true;auto state=c->state;auto id=c->id;HWND destination=g_main;std::thread([state,id,destination]{auto result=new NetResult;result->id=id;result->identity=identity(state);try{result->data=weatherRequest(state);}catch(const std::exception& e){result->error=wide(e.what());}if(!PostMessageW(destination,WM_NET,0,(LPARAM)result))delete result;}).detach();}}
struct CityContext{HWND dialog=nullptr;std::vector<json> rows;json selected;unsigned generation=0;};CityContext* g_city=nullptr;unsigned g_generation=0;
void fillCities(CityContext* c){SendDlgItemMessageW(c->dialog,IDC_RESULTS,LB_RESETCONTENT,0,0);for(auto& r:c->rows){auto label=wide(str(r,"name")+"  "+str(r,"region")+"  ["+str(r,"zone")+"]");SendDlgItemMessageW(c->dialog,IDC_RESULTS,LB_ADDSTRING,0,(LPARAM)label.c_str());}}
void searchCities(CityContext* c){wchar_t query[256];GetDlgItemTextW(c->dialog,IDC_QUERY,query,256);if(wcslen(query)<2){SetDlgItemTextW(c->dialog,IDC_STATUS,L"请输入至少两个字符，可使用英文城市名。");return;}c->generation=++g_generation;c->rows.clear();fillCities(c);SetDlgItemTextW(c->dialog,IDC_STATUS,L"正在联网搜索…");auto term=utf8(query);auto generation=c->generation;HWND destination=g_main;std::thread([term,generation,destination]{auto r=new NetResult;r->search=true;r->generation=generation;try{r->data=https(L"geocoding-api.open-meteo.com",L"/v1/search?count=20&language=zh&format=json&name="+escaped(term));}catch(const std::exception& e){r->error=wide(e.what());}if(!PostMessageW(destination,WM_NET,0,(LPARAM)r))delete r;}).detach();}
INT_PTR CALLBACK CityProc(HWND h,UINT m,WPARAM w,LPARAM l){auto c=(CityContext*)GetWindowLongPtrW(h,DWLP_USER);if(m==WM_INITDIALOG){SendMessageW(h,WM_SETICON,ICON_SMALL,(LPARAM)g_iconSmall);SendMessageW(h,WM_SETICON,ICON_BIG,(LPARAM)g_iconLarge);c=(CityContext*)l;c->dialog=h;SetWindowLongPtrW(h,DWLP_USER,l);fillCities(c);return TRUE;}if(!c)return FALSE;if(m==WM_COMMAND){int id=LOWORD(w);if(id==IDC_SEARCH){searchCities(c);return TRUE;}if(id==IDOK||(id==IDC_RESULTS&&HIWORD(w)==LBN_DBLCLK)){if(GetFocus()==GetDlgItem(h,IDC_QUERY)){searchCities(c);return TRUE;}int index=(int)SendDlgItemMessageW(h,IDC_RESULTS,LB_GETCURSEL,0,0);if(index>=0&&index<(int)c->rows.size()){c->selected=c->rows[index];EndDialog(h,IDOK);}return TRUE;}if(id==IDCANCEL){EndDialog(h,IDCANCEL);return TRUE;}}return FALSE;}
void chooseCity(Card* target){if(!target&&g_cards.size()>=30){notify(L"卡片数量",L"最多支持 30 张卡片。");return;}CityContext context;context.rows=presets();context.generation=++g_generation;g_city=&context;auto result=DialogBoxParamW(g_instance,MAKEINTRESOURCEW(IDD_CITY),target?target->hwnd:g_main,CityProc,(LPARAM)&context);g_city=nullptr;if(result==IDOK&&!context.selected.is_null()){if(target){for(auto it=context.selected.begin();it!=context.selected.end();++it)target->state[it.key()]=it.value();target->state.erase("weather");target->retryAt=0;updateCard(target);}else{context.selected["x"]=100+24*(int)g_cards.size();context.selected["y"]=180;addCard(context.selected);}save();refresh(true,target);}}
// Copy appearance only. Identity, coordinates, weather cache and window position stay local.
void copyAppearance(Card* source,Card* destination){
    if(!source||!destination||source==destination)return;
    for(auto key:{"top","glass","theme","color_mode","color","transparency","show"})
        destination->state[key]=source->state.at(key);
    updateCard(destination);
}
void syncAppearance(Card* source,uint64_t target){
    for(auto& item:g_cards)if(item.get()!=source&&(target==0||item->id==target))copyAppearance(source,item.get());
    save();refresh();
}
int g_testDialogs=0;
struct SettingsContext{Card* card;json original;bool ready=false,updating=false;};
void preview(HWND h,SettingsContext* ctx){if(!ctx->ready)return;auto c=ctx->card;c->state["top"]=IsDlgButtonChecked(h,IDC_TOP)==BST_CHECKED;c->state["glass"]=IsDlgButtonChecked(h,IDC_GLASS)==BST_CHECKED;int theme=(int)SendDlgItemMessageW(h,IDC_THEME,CB_GETCURSEL,0,0);c->state["theme"]=theme==1?"light":theme==2?"dark":"system";c->state["color_mode"]=IsDlgButtonChecked(h,IDC_CUSTOM)==BST_CHECKED?"custom":"system";for(int i=0;i<9;i++)c->state["show"][SHOW_KEYS[i]]=IsDlgButtonChecked(h,IDC_SHOW_CITY+i)==BST_CHECKED;updateCard(c);}
INT_PTR CALLBACK SettingsProc(HWND h,UINT m,WPARAM w,LPARAM l){auto ctx=(SettingsContext*)GetWindowLongPtrW(h,DWLP_USER);if(m==WM_INITDIALOG){SendMessageW(h,WM_SETICON,ICON_SMALL,(LPARAM)g_iconSmall);SendMessageW(h,WM_SETICON,ICON_BIG,(LPARAM)g_iconLarge);ctx=(SettingsContext*)l;SetWindowLongPtrW(h,DWLP_USER,l);auto& s=ctx->card->state;CheckDlgButton(h,IDC_TOP,flag(s,"top",true));CheckDlgButton(h,IDC_GLASS,flag(s,"glass",true));CheckDlgButton(h,IDC_CUSTOM,str(s,"color_mode")=="custom");for(auto label:{L"跟随系统",L"白天（浅色）",L"夜晚（深色）"})SendDlgItemMessageW(h,IDC_THEME,CB_ADDSTRING,0,(LPARAM)label);SendDlgItemMessageW(h,IDC_THEME,CB_SETCURSEL,str(s,"theme")=="light"?1:str(s,"theme")=="dark"?2:0,0);SendDlgItemMessageW(h,IDC_ALPHA,TBM_SETRANGE,TRUE,MAKELONG(0,100));SendDlgItemMessageW(h,IDC_ALPHA,TBM_SETPOS,TRUE,(LPARAM)number(s,"transparency",18));SetDlgItemInt(h,IDC_ALPHA_NUMBER,(UINT)number(s,"transparency",18),FALSE);for(int i=0;i<9;i++)CheckDlgButton(h,IDC_SHOW_CITY+i,flag(s["show"],SHOW_KEYS[i]));SendDlgItemMessageW(h,IDC_SYNC,CB_ADDSTRING,0,(LPARAM)L"仅当前卡片");SendDlgItemMessageW(h,IDC_SYNC,CB_ADDSTRING,0,(LPARAM)L"同步到全部卡片");
for(auto& item:g_cards)if(item.get()!=ctx->card){auto label=wide(str(item->state,"name")+" ["+str(item->state,"zone")+"] #"+std::to_string(item->id));int index=(int)SendDlgItemMessageW(h,IDC_SYNC,CB_ADDSTRING,0,(LPARAM)label.c_str());SendDlgItemMessageW(h,IDC_SYNC,CB_SETITEMDATA,index,(LPARAM)item->id);}
SendDlgItemMessageW(h,IDC_SYNC,CB_SETCURSEL,0,0);ctx->ready=true;if(g_testing){++g_testDialogs;PostMessageW(h,WM_COMMAND,IDCANCEL,0);}return TRUE;}if(!ctx)return FALSE;
if(m==WM_HSCROLL&&ctx->ready){int v=(int)SendDlgItemMessageW(h,IDC_ALPHA,TBM_GETPOS,0,0);ctx->card->state["transparency"]=v;ctx->updating=true;SetDlgItemInt(h,IDC_ALPHA_NUMBER,v,FALSE);ctx->updating=false;refreshStyle(ctx->card);InvalidateRect(ctx->card->hwnd,nullptr,FALSE);return TRUE;}
if(m==WM_COMMAND){int id=LOWORD(w);if(id==IDC_ALPHA_NUMBER&&HIWORD(w)==EN_CHANGE&&ctx->ready&&!ctx->updating){BOOL ok;UINT v=GetDlgItemInt(h,IDC_ALPHA_NUMBER,&ok,FALSE);if(ok){v=std::min(v,100u);ctx->card->state["transparency"]=v;SendDlgItemMessageW(h,IDC_ALPHA,TBM_SETPOS,TRUE,v);refreshStyle(ctx->card);InvalidateRect(ctx->card->hwnd,nullptr,FALSE);}return TRUE;}
if(id==IDC_COLOR){static COLORREF custom[16]{};auto bg=background(ctx->card);CHOOSECOLORW cc{sizeof(cc)};cc.hwndOwner=h;cc.lpCustColors=custom;cc.Flags=CC_FULLOPEN|CC_RGBINIT;cc.rgbResult=RGB((int)(bg.r*255),(int)(bg.g*255),(int)(bg.b*255));if(ChooseColorW(&cc)){char color[8];sprintf_s(color,"#%02x%02x%02x",GetRValue(cc.rgbResult),GetGValue(cc.rgbResult),GetBValue(cc.rgbResult));ctx->card->state["color"]=color;CheckDlgButton(h,IDC_CUSTOM,BST_CHECKED);preview(h,ctx);}return TRUE;}
if(id==IDOK){preview(h,ctx);int selection=(int)SendDlgItemMessageW(h,IDC_SYNC,CB_GETCURSEL,0,0);if(selection>0)syncAppearance(ctx->card,selection==1?0:(uint64_t)SendDlgItemMessageW(h,IDC_SYNC,CB_GETITEMDATA,selection,0));save();EndDialog(h,IDOK);return TRUE;}if(id==IDCANCEL){auto cache=ctx->card->state.value("weather",json::object());ctx->card->state=ctx->original;if(!cache.empty())ctx->card->state["weather"]=cache;updateCard(ctx->card);save();EndDialog(h,IDCANCEL);return TRUE;}if(HIWORD(w)==BN_CLICKED||HIWORD(w)==CBN_SELCHANGE)preview(h,ctx);}if(m==WM_CLOSE){SendMessageW(h,WM_COMMAND,IDCANCEL,0);return TRUE;}return FALSE;}
void cardSettings(Card* c){SettingsContext ctx{c,c->state};DialogBoxParamW(g_instance,MAKEINTRESOURCEW(IDD_SETTINGS),c->hwnd,SettingsProc,(LPARAM)&ctx);refresh(false,c);}
void alignPair(Card* anchor,Card* other,bool horizontal){RECT a,b;GetWindowRect(anchor->hwnd,&a);GetWindowRect(other->hwnd,&b);int gap=anchor->px(12),x=horizontal?a.right+gap:a.left,y=horizontal?a.top:a.bottom+gap;auto area=workArea(anchor->hwnd);if(horizontal&&x+b.right-b.left>area.right)x=a.left-gap-(b.right-b.left);if(!horizontal&&y+b.bottom-b.top>area.bottom)y=a.top-gap-(b.bottom-b.top);SetWindowPos(other->hwnd,nullptr,x,y,0,0,SWP_NOZORDER|SWP_NOSIZE|SWP_NOACTIVATE);clampCard(other);save();}
void alignAll(bool horizontal){if(g_cards.empty())return;auto first=g_cards.front().get();auto area=workArea(first->hwnd);RECT a;GetWindowRect(first->hwnd,&a);int total=0,cross=0,gap=first->px(12);for(auto& c:g_cards){RECT r;GetWindowRect(c->hwnd,&r);total+=(horizontal?r.right-r.left:r.bottom-r.top)+gap;cross=std::max(cross,(int)(horizontal?r.bottom-r.top:r.right-r.left));}total-=gap;if(total>(horizontal?area.right-area.left:area.bottom-area.top)||cross>(horizontal?area.bottom-area.top:area.right-area.left)){notify(L"空间不足",L"当前屏幕无法放下全部卡片，请使用两张卡片的对齐菜单。");return;}int x=std::clamp((int)a.left,(int)area.left,(int)area.right-(horizontal?total:cross)),y=std::clamp((int)a.top,(int)area.top,(int)area.bottom-(horizontal?cross:total));for(auto& c:g_cards){RECT r;GetWindowRect(c->hwnd,&r);SetWindowPos(c->hwnd,nullptr,x,y,0,0,SWP_NOZORDER|SWP_NOSIZE|SWP_NOACTIVATE);if(horizontal)x+=r.right-r.left+gap;else y+=r.bottom-r.top+gap;}save();}
void snap(Card* c){RECT a;GetWindowRect(c->hwnd,&a);int x=a.left,y=a.top,gap=c->px(12),distance=c->px(10);for(auto& other:g_cards)if(other.get()!=c){RECT b;GetWindowRect(other->hwnd,&b);if(abs(a.top-b.top)<distance)y=b.top;if(abs(a.left-b.left)<distance)x=b.left;if(abs(a.left-b.right-gap)<distance)x=b.right+gap;if(abs(a.top-b.bottom-gap)<distance)y=b.bottom+gap;}SetWindowPos(c->hwnd,nullptr,x,y,0,0,SWP_NOZORDER|SWP_NOSIZE|SWP_NOACTIVATE);clampCard(c);save();}
struct QuickAction{uint64_t target;int action;};std::map<int,QuickAction> quickActions;
void menu(Card* c,POINT p);
void quickDispatch(QuickAction choice){
    Card* selected=choice.target?findCard(choice.target):nullptr;if(choice.target&&!selected)return;

    std::vector<Card*> targets;for(auto& item:g_cards)if(!selected||item.get()==selected)targets.push_back(item.get());if(targets.empty())return;
    auto first=targets.front();json value;std::string key;
    if(choice.action<=10){key="transparency";value=choice.action*10;}
    else if(choice.action>=20&&choice.action<=22){key="theme";value=choice.action==20?"system":choice.action==21?"light":"dark";}
    else if(choice.action==31){key="color_mode";value="system";}
    else if(choice.action==50||choice.action==51){key=choice.action==50?"top":"glass";bool all=true;for(auto c:targets)all=all&&flag(c->state,key.c_str());value=!all;}
    else if(choice.action>=40&&choice.action<=48){key=SHOW_KEYS[choice.action-40];bool all=true;for(auto c:targets)all=all&&flag(c->state["show"],key.c_str());for(auto c:targets)c->state["show"][key]=!all;key.clear();}
    else if(choice.action==30){static COLORREF custom[16]{};auto bg=background(first);CHOOSECOLORW cc{sizeof(cc)};cc.hwndOwner=selected?selected->hwnd:g_main;cc.lpCustColors=custom;cc.Flags=CC_FULLOPEN|CC_RGBINIT;cc.rgbResult=RGB((int)(bg.r*255),(int)(bg.g*255),(int)(bg.b*255));if(!ChooseColorW(&cc))return;char color[8];sprintf_s(color,"#%02x%02x%02x",GetRValue(cc.rgbResult),GetGValue(cc.rgbResult),GetBValue(cc.rgbResult));for(auto c:targets){c->state["color_mode"]="custom";c->state["color"]=color;}}
    for(auto c:targets){if(!key.empty())c->state[key]=value;updateCard(c);}save();refresh();
}
void appendQuickMenu(HMENU m,Card* selected){
    std::vector<Card*> targets;for(auto& item:g_cards)if(!selected||selected==item.get())targets.push_back(item.get());
    auto all=[&](const char* key,const json& value,bool show=false){if(targets.empty())return false;for(auto c:targets){auto& data=show?c->state["show"]:c->state;if(!data.contains(key)||data[key]!=value)return false;}return true;};
    auto entry=[&](HMENU into,int action,const std::wstring& text,bool check=false){int id=10000+(int)quickActions.size();quickActions[id]={selected?selected->id:0,action};AppendMenuW(into,MF_STRING|(check?MF_CHECKED:0),id,text.c_str());};
    HMENU opacity=CreatePopupMenu();for(int i=0;i<=10;i++)entry(opacity,i,std::to_wstring(i*10)+L"%"+(i==0?L"（透出桌面）":L""),all("transparency",i*10));AppendMenuW(m,MF_POPUP,(UINT_PTR)opacity,L"透明度 / Alpha（0–100）");
    HMENU theme=CreatePopupMenu();entry(theme,20,L"跟随系统",all("theme","system"));entry(theme,21,L"浅色",all("theme","light"));entry(theme,22,L"深色",all("theme","dark"));AppendMenuW(m,MF_POPUP,(UINT_PTR)theme,L"外观模式");
    HMENU colors=CreatePopupMenu();entry(colors,31,L"跟随外观模式",all("color_mode","system"));entry(colors,30,L"选择卡片颜色…");AppendMenuW(m,MF_POPUP,(UINT_PTR)colors,L"卡片颜色");
    HMENU shows=CreatePopupMenu();const wchar_t* labels[]={L"城市",L"地区",L"日期",L"星期",L"时差",L"天气",L"秒",L"太阳 / 月亮",L"日出 / 日落"};for(int i=0;i<9;i++)entry(shows,40+i,labels[i],all(SHOW_KEYS[i],true,true));AppendMenuW(m,MF_POPUP,(UINT_PTR)shows,L"显示项");
    entry(m,50,L"置顶",all("top",true));entry(m,51,L"自绘磨砂",all("glass",true));
    if(selected){entry(m,52,L"详细设置 / 同步到其他卡片…");entry(m,54,L"更换城市…");entry(m,53,L"移除此城市");}
}

void dispatch(int cmd,Card* c){if(cmd>=10000){auto it=quickActions.find(cmd);if(it==quickActions.end())return;auto action=it->second;auto target=findCard(action.target);if(action.action>=52){if(target)dispatch(action.action==52?CMD_SETTINGS:action.action==53?CMD_REMOVE:CMD_CHANGE,target);}else quickDispatch(action);return;}if(cmd>=CMD_ALIGN_BASE){size_t index=(cmd-CMD_ALIGN_BASE)/2;if(c&&index<g_cards.size())alignPair(c,g_cards[index].get(),(cmd-CMD_ALIGN_BASE)%2==0);return;}switch(cmd){case CMD_ADD:chooseCity();break;case CMD_CHANGE:if(c)chooseCity(c);break;case CMD_SETTINGS:if(c)cardSettings(c);break;case CMD_SAVE:save(true);break;case CMD_EXPORT:exportSettings();break;case CMD_STARTUP:if(!setAutoStart(!autoStart()))notify(L"设置失败",L"无法修改当前用户的开机自启设置。");break;case CMD_HORIZONTAL:alignAll(true);break;case CMD_VERTICAL:alignAll(false);break;case CMD_WEATHER:refresh(true,c);break;case CMD_SHOW:for(auto& item:g_cards){ShowWindow(item->hwnd,SW_SHOWNOACTIVATE);updateCard(item.get());}break;case CMD_REMOVE:if(c){if(g_cards.size()==1){PostMessageW(g_main,WM_CLOSE,0,0);break;}auto it=std::find_if(g_cards.begin(),g_cards.end(),[c](auto& ptr){return ptr.get()==c;});if(it!=g_cards.end()){DestroyWindow(c->hwnd);g_cards.erase(it);save();}}break;case CMD_ABOUT:MessageBoxW(c?c->hwnd:g_main,L"世界时钟 2.0.0 · 原生 C++\n\n拖动卡片移动，右键设置、对齐。\n磨砂通过截图、缩放模糊和抗锯齿合成，\n并开启 Windows 的透明效果。节电模式可能降低效果。\n\n天气及城市搜索：Open-Meteo（CC BY 4.0）。\n仅发送所选城市坐标/搜索词，不读取设备定位。\n开机自启默认关闭。",L"关于世界时钟",MB_OK);break;case CMD_EXIT:PostMessageW(g_main,WM_CLOSE,0,0);break;}}
void menu(Card* c,POINT p){HMENU m=CreatePopupMenu();quickActions.clear();if(!c){AppendMenuW(m,MF_STRING|MF_DISABLED,0,L"以下快捷设置应用到全部卡片");appendQuickMenu(m,nullptr);HMENU cards=CreatePopupMenu();for(auto& item:g_cards){HMENU card=CreatePopupMenu();appendQuickMenu(card,item.get());auto title=wide(str(item->state,"name")+" ["+str(item->state,"zone")+"] #"+std::to_string(item->id));AppendMenuW(cards,MF_POPUP,(UINT_PTR)card,title.c_str());}AppendMenuW(m,MF_POPUP,(UINT_PTR)cards,L"单独设置 / 移除城市");AppendMenuW(m,MF_SEPARATOR,0,nullptr);}if(c){appendQuickMenu(m,c);AppendMenuW(m,MF_STRING,CMD_SETTINGS,L"卡片设置…");HMENU alignment=CreatePopupMenu();for(size_t i=0;i<g_cards.size();i++)if(g_cards[i].get()!=c){std::wstring name=wide(str(g_cards[i]->state,"name"));AppendMenuW(alignment,MF_STRING,CMD_ALIGN_BASE+i*2,(L"与 "+name+L" 水平排列").c_str());AppendMenuW(alignment,MF_STRING,CMD_ALIGN_BASE+i*2+1,(L"与 "+name+L" 垂直排列").c_str());}AppendMenuW(m,MF_POPUP,(UINT_PTR)alignment,L"两张卡片对齐");AppendMenuW(m,MF_STRING,CMD_CHANGE,L"更换城市…");}AppendMenuW(m,MF_STRING,CMD_ADD,L"添加城市…");AppendMenuW(m,MF_STRING,CMD_HORIZONTAL,L"全部水平排列");AppendMenuW(m,MF_STRING,CMD_VERTICAL,L"全部垂直排列");AppendMenuW(m,MF_STRING,CMD_SAVE,L"保存当前位置和设置");if(!c){AppendMenuW(m,MF_STRING,CMD_EXPORT,L"导出设置到文件…");AppendMenuW(m,MF_STRING|(autoStart()?MF_CHECKED:0),CMD_STARTUP,L"开机自启");AppendMenuW(m,MF_STRING,CMD_SHOW,L"显示全部卡片");}AppendMenuW(m,MF_STRING,CMD_WEATHER,L"刷新天气");if(c)AppendMenuW(m,MF_STRING,CMD_REMOVE,L"删除此卡片");AppendMenuW(m,MF_SEPARATOR,0,nullptr);AppendMenuW(m,MF_STRING,CMD_ABOUT,L"关于");AppendMenuW(m,MF_STRING,CMD_EXIT,L"退出");HWND owner=c?c->hwnd:g_main;SetForegroundWindow(owner);int cmd=g_testing?CMD_SETTINGS:TrackPopupMenu(m,TPM_RETURNCMD|TPM_RIGHTBUTTON,p.x,p.y,0,owner,nullptr);DestroyMenu(m);PostMessageW(owner,WM_NULL,0,0);dispatch(cmd,c);}
LRESULT CALLBACK CardProc(HWND h,UINT m,WPARAM w,LPARAM l){auto c=(Card*)GetWindowLongPtrW(h,GWLP_USERDATA);if(m==WM_NCCREATE){c=(Card*)((CREATESTRUCTW*)l)->lpCreateParams;c->hwnd=h;SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)c);}if(!c)return DefWindowProcW(h,m,w,l);switch(m){case WM_NCCALCSIZE:if(w)return 0;break;case WM_NCHITTEST:return HTCLIENT;case WM_CREATE:SetTimer(h,1,250,nullptr);return 0;case WM_ERASEBKGND:return 1;case WM_PAINT:paint(c);return 0;case WM_TIMER:paint(c);return 0;case WM_LBUTTONDOWN:{POINT pt;GetCursorPos(&pt);ReleaseCapture();SendMessageW(h,WM_NCLBUTTONDOWN,HTCAPTION,MAKELPARAM(pt.x,pt.y));return 0;}case WM_EXITSIZEMOVE:snap(c);return 0;case WM_RBUTTONUP:{POINT p;GetCursorPos(&p);menu(c,p);return 0;}case WM_NCRBUTTONUP:{POINT p;GetCursorPos(&p);menu(c,p);return 0;}case WM_CONTEXTMENU:{POINT p{GET_X_LPARAM(l),GET_Y_LPARAM(l)};if(p.x==-1)GetCursorPos(&p);menu(c,p);return 0;}case WM_SIZE:resetGraphics(c);InvalidateRect(h,nullptr,FALSE);return 0;case WM_DPICHANGED:{c->dpi=(float)HIWORD(w);auto r=(RECT*)l;SetWindowPos(h,nullptr,r->left,r->top,c->px(260),c->px(c->height()),SWP_NOZORDER|SWP_NOACTIVATE);resetGraphics(c);InvalidateRect(h,nullptr,FALSE);return 0;}case WM_SETTINGCHANGE:case WM_THEMECHANGED:case WM_DWMCOMPOSITIONCHANGED:refreshStyle(c);InvalidateRect(h,nullptr,FALSE);return 0;case WM_DESTROY:KillTimer(h,1);resetGraphics(c);return 0;}return DefWindowProcW(h,m,w,l);}
LRESULT CALLBACK MainProc(HWND h,UINT m,WPARAM w,LPARAM l){if(g_taskbarCreated&&m==g_taskbarCreated){tray();return 0;}switch(m){case WM_TRAY:if(l==WM_RBUTTONUP||l==WM_CONTEXTMENU){POINT p;GetCursorPos(&p);menu(nullptr,p);}else if(l==WM_LBUTTONDBLCLK)dispatch(CMD_SHOW,nullptr);return 0;case WM_TIMER:refresh();return 0;case WM_SETTINGCHANGE:case WM_THEMECHANGED:for(auto& c:g_cards){refreshStyle(c.get());InvalidateRect(c->hwnd,nullptr,FALSE);}return 0;case WM_NET:{std::unique_ptr<NetResult> r((NetResult*)l);if(g_quitting)return 0;if(r->search){if(!g_city||r->generation!=g_city->generation)return 0;auto c=g_city;if(!r->error.empty()){SetDlgItemTextW(c->dialog,IDC_STATUS,L"联网搜索失败，请检查网络后重试。");return 0;}auto rows=r->data.value("results",json::array());for(auto& row:rows){auto zone=str(row,"timezone");if(!zoneSupported(zone)||!row.contains("latitude")||!row.contains("longitude"))continue;auto region=str(row,"admin1"),country=str(row,"country");if(region!=country&&!country.empty())region+=(region.empty()?"":" · ")+country;c->rows.push_back({{"name",str(row,"name")},{"region",region},{"zone",zone},{"lat",row["latitude"]},{"lon",row["longitude"]}});}fillCities(c);SetDlgItemTextW(c->dialog,IDC_STATUS,c->rows.empty()?L"未找到支持的城市，请尝试英文名称。":L"请选择城市后点击确定。数据：Open-Meteo");}else{auto c=findCard(r->id);if(!c)return 0;c->pending=false;if(r->identity!=identity(c->state)){refresh(true,c);return 0;}if(r->error.empty()){c->state["weather"]=r->data;c->error.clear();c->retryAt=0;save();}else{c->error=r->error;c->retryAt=nowSeconds()+300;}InvalidateRect(c->hwnd,nullptr,FALSE);}return 0;}case WM_CLOSE:{g_quitting=true;save();NOTIFYICONDATAW n{sizeof(n)};n.hWnd=h;n.uID=1;Shell_NotifyIconW(NIM_DELETE,&n);for(auto& c:g_cards)DestroyWindow(c->hwnd);g_cards.clear();DestroyWindow(h);return 0;}case WM_DESTROY:PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
void pump(){MSG msg;while(PeekMessageW(&msg,nullptr,0,0,PM_REMOVE)){TranslateMessage(&msg);DispatchMessageW(&msg);}}
void require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
int selfTest(const fs::path& report,bool online){g_testing=true;g_config=report;g_config+=L".settings.json";try{auto p=presets();p[0]["x"]=100;p[0]["y"]=100;p[1]["x"]=420;p[1]["y"]=100;addCard(p[0]);addCard(p[1]);pump();auto a=g_cards[0].get(),b=g_cards[1].get();require(a->target!=nullptr,"WIC/layered initialization failed");require((GetWindowLongPtrW(a->hwnd,GWL_EXSTYLE)&WS_EX_TOPMOST)!=0,"Default topmost failed");require((GetWindowLongPtrW(a->hwnd,GWL_EXSTYLE)&WS_EX_LAYERED)!=0,"Layered style missing");alignPair(a,b,true);RECT ar,br;GetWindowRect(a->hwnd,&ar);GetWindowRect(b->hwnd,&br);require(ar.top==br.top&&br.left>=ar.right,"Horizontal alignment failed");alignPair(a,b,false);GetWindowRect(a->hwnd,&ar);GetWindowRect(b->hwnd,&br);require(ar.left==br.left&&br.top>=ar.bottom,"Vertical alignment failed");for(int value:{0,50,100}){a->state["transparency"]=value;updateCard(a);paint(a);require(SUCCEEDED(a->renderResult),"Layered presentation failed");require(std::abs(a->testBackgroundAlpha-(int)std::lround(value*255/100.0))<=1,"Background alpha mismatch");if(value==100)require(a->testSoftEdges>0,"Antialiased corner missing");}
a->state["transparency"]=0;updateCard(a);paint(a);pump();
require(SUCCEEDED(a->renderResult)&&a->bitmap!=nullptr,"Composition rendering failed");
require(a->testCornerAlpha==0&&a->testBackgroundAlpha==0&&a->testMaxAlpha==255,"Zero must preserve transparent background and opaque text");
a->state["transparency"]=50;
a->state["weather"]={{"current_time",nowSeconds()},{"is_day",0}};updateCard(a);paint(a);require(SUCCEEDED(a->renderResult),"Moon geometry render failed");
a->state["weather"]["is_day"]=1;paint(a);require(SUCCEEDED(a->renderResult),"Sun render failed");a->state.erase("weather");
a->state["color_mode"]="custom";a->state["color"]="#123456";require(std::abs(background(a).r-18/255.f)<.001,"Custom color failed");for(auto k:SHOW_KEYS)a->state["show"][k]=false;require(a->height()==68,"Content toggles failed");a->state["show"]=defaultShow();a->state["transparency"]=40;updateCard(a);pump();double epoch=1768478400;auto utc=systemAt(epoch),lusaka=localAt("Africa/Lusaka",epoch);require(ticksOf(lusaka)-ticksOf(utc)==72000000000LL,"Lusaka UTC+2 failed");double now=nowSeconds();json w={{"days",json::array({{{"date",dateOf(localAt("Africa/Lusaka",now))},{"rise",now-3600},{"set",now+3600}}})}};require(sunFor(w,"Africa/Lusaka",now).day==1,"Sunrise classification failed");require(sunFor(w,"Africa/Lusaka",now-7200).day==0,"Night classification failed");HMENU testMenu=CreatePopupMenu();quickActions.clear();appendQuickMenu(testMenu,nullptr);require(GetMenuItemCount(testMenu)==6,"Tray quick menu sections missing");DestroyMenu(testMenu);
quickDispatch({a->id,3});require(number(a->state,"transparency")==30&&number(b->state,"transparency")!=30,"Per-card tray setting leaked");quickDispatch({0,5});require(number(a->state,"transparency")==50&&number(b->state,"transparency")==50,"All-card tray setting failed");
quickDispatch({0,22});require(str(a->state,"theme")=="dark"&&str(b->state,"theme")=="dark","Tray theme failed");
require(SendMessageW(a->hwnd,WM_NCHITTEST,0,0)==HTCLIENT,"Right click incorrectly classified as caption");
int dialogsBefore=g_testDialogs;SendMessageW(a->hwnd,WM_RBUTTONUP,0,0);SendMessageW(a->hwnd,WM_CONTEXTMENU,(WPARAM)a->hwnd,MAKELPARAM(-1,-1));require(g_testDialogs==dialogsBefore+2,"Right click/settings dialog route failed");
RECT captureBefore,captureAfter;GetWindowRect(a->hwnd,&captureBefore);for(int i=0;i<12;i++){a->captureAt=0;paint(a);require(SUCCEEDED(a->renderResult)&&IsWindowVisible(a->hwnd),"Refresh blanked or hid card");}GetWindowRect(a->hwnd,&captureAfter);require(EqualRect(&captureBefore,&captureAfter),"Capture moved card");require(a->blur!=nullptr,"Blur pipeline failed");
auto before=b->state;b->state["weather"]={{"temp",27.0}};RECT beforeRect;GetWindowRect(b->hwnd,&beforeRect);
a->state["theme"]="dark";a->state["show"]["seconds"]=false;syncAppearance(a,b->id);
require(b->state["theme"]=="dark"&&!flag(b->state["show"],"seconds"),"Selected sync failed");
require(b->state["zone"]==before["zone"]&&b->state["name"]==before["name"]&&number(b->state["weather"],"temp")==27,"Sync changed city/weather");RECT afterRect;GetWindowRect(b->hwnd,&afterRect);require(beforeRect.left==afterRect.left&&beforeRect.top==afterRect.top,"Sync moved destination");
auto third=presets()[2];addCard(third);auto d=g_cards.back().get();auto thirdBefore=d->state;a->state["transparency"]=73;syncAppearance(a,b->id);require(d->state==thirdBefore,"Selected sync affected another card");syncAppearance(a,0);require(number(d->state,"transparency")==73&&d->state["zone"]==thirdBefore["zone"],"Sync all failed");DestroyWindow(d->hwnd);g_cards.pop_back();
save();std::ifstream in(g_config);auto stored=json::parse(in);require(stored["cards"].size()==2,"Position persistence failed");json result={{"version","2.0.0"},{"engine","MSVC static CRT / WIC / UpdateLayeredWindow"},{"passed",true},{"checks",{"UpdateLayeredWindow presentation","antialiased rounded edge","zero background alpha / opaque text","night and day geometry rendering","default topmost","linear Alpha 0/50/100","horizontal alignment","vertical alignment","transparency 0/50/100","custom color","content toggles","Lusaka UTC+2","sunrise/sunset","JSON persistence","selected sync isolation","sync preserves city/weather/position","sync all","tray scopes and theme","right click opens settings dialog","12 refreshes preserve visibility and position","downsample/upsample blur pipeline"}}};result["live_desktop_capture"]=a->captureOK;result["screen_capture_error"]=a->captureError;result["blur_fixture_used"]=a->testBlurFixture;if(online){auto weather=weatherRequest(presets()[2]);require(weather["temp"].is_number()&&!weather["days"].empty(),"Live weather failed");auto cities=https(L"geocoding-api.open-meteo.com",L"/v1/search?name=Lusaka&count=5&language=zh&format=json");require(cities.contains("results")&&!cities["results"].empty(),"City search failed");result["live_weather"]=weather;result["search_results"]=cities["results"].size();}writeSettings(report,result);return 0;}catch(const std::exception& e){writeSettings(report,{{"passed",false},{"error",e.what()}});return 1;}}
int WINAPI wWinMain(HINSTANCE instance,HINSTANCE,PWSTR,int){g_instance=instance;g_iconSmall=(HICON)LoadImageW(instance,MAKEINTRESOURCEW(IDI_WORLD_CLOCK),IMAGE_ICON,GetSystemMetrics(SM_CXSMICON),GetSystemMetrics(SM_CYSMICON),LR_SHARED);g_iconLarge=LoadIconW(instance,MAKEINTRESOURCEW(IDI_WORLD_CLOCK));SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(CoCreateInstance(CLSID_WICImagingFactory,nullptr,CLSCTX_INPROC_SERVER,IID_PPV_ARGS(&g_wic))))return 2;INITCOMMONCONTROLSEX controls{sizeof(controls),ICC_STANDARD_CLASSES|ICC_BAR_CLASSES};InitCommonControlsEx(&controls);initZones();if(FAILED(D2D1CreateFactory(D2D1_FACTORY_TYPE_SINGLE_THREADED,g_d2d.GetAddressOf()))||FAILED(DWriteCreateFactory(DWRITE_FACTORY_TYPE_SHARED,__uuidof(IDWriteFactory),(IUnknown**)g_write.GetAddressOf())))return 2;WNDCLASSW mainClass{};mainClass.lpfnWndProc=MainProc;mainClass.hInstance=instance;mainClass.hIcon=g_iconLarge;mainClass.lpszClassName=L"WorldClockController";RegisterClassW(&mainClass);WNDCLASSW cardClass{};cardClass.lpfnWndProc=CardProc;cardClass.hInstance=instance;cardClass.hIcon=g_iconLarge;cardClass.lpszClassName=L"WorldClockCard";cardClass.hCursor=LoadCursorW(nullptr,IDC_ARROW);RegisterClassW(&cardClass);g_taskbarCreated=RegisterWindowMessageW(L"TaskbarCreated");g_main=CreateWindowExW(WS_EX_TOOLWINDOW,mainClass.lpszClassName,L"World Clock",WS_POPUP,0,0,0,0,nullptr,nullptr,instance,nullptr);int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(argc>=3&&(std::wstring(argv[1])==L"--self-test"||std::wstring(argv[1])==L"--network-test")){int result=selfTest(argv[2],std::wstring(argv[1])==L"--network-test");LocalFree(argv);return result;}bool startup=argc>1&&std::wstring(argv[1])==L"--startup";fs::path previewPath;if(argc>=3&&std::wstring(argv[1])==L"--preview")previewPath=argv[2];LocalFree(argv);HANDLE mutex=CreateMutexW(nullptr,FALSE,L"Local\\WorldClockNativeCpp");if(GetLastError()==ERROR_ALREADY_EXISTS){if(!startup)MessageBoxW(nullptr,L"世界时钟已在运行，请查看系统托盘。",L"世界时钟",MB_OK);return 0;}PWSTR appdata=nullptr;if(FAILED(SHGetKnownFolderPath(FOLDERID_RoamingAppData,0,nullptr,&appdata)))return 3;g_config=fs::path(appdata)/L"WorldClockPython"/L"clocks.json";CoTaskMemFree(appdata);if(!previewPath.empty())g_config=previewPath;try{load();tray();SetTimer(g_main,1,60000,nullptr);refresh();MSG msg;while(GetMessageW(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}}catch(const std::exception& e){MessageBoxW(nullptr,wide(e.what()).c_str(),L"世界时钟启动失败",MB_OK|MB_ICONERROR);return 1;}CloseHandle(mutex);CoUninitialize();return 0;}







